services:
  db:
    image: mysql:9
    container_name: secure_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/my.cnf:/etc/mysql/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sca_network

  sca-server:
    image: ghcr.io/fontys-pingmasters/sca-server:testing
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - FRONT_END_URL=https://test.pongello.nl
      - DB_HOST="db"
      - DB_NAME="securedb"
      - DB_USER="swremotedb"
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=60
      - JWT_AUDIENCE=https://test.pongello.nl
      - JWT_ISSUER=https://test.pongello.nl
    depends_on:
      db:
        condition: service_healthy
    networks:
      - sca_network

volumes:
  db_data:

networks:
  sca_network:
    driver: bridge
    attachable: true
