kind: Deployment
apiVersion: apps/v1
metadata:
  name: sca-api
spec:
  selector:
    matchLabels:
      app: sca-api
  template:
    metadata:
      labels:
        app: sca-api
    spec:
      containers:
        - name: sca-api
          image: ghcr.io/fontys-pingmasters/sca-server
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "250m"