kind: Deployment
apiVersion: apps/v1
metadata:
  name: sca-server
spec:
  selector:
    matchLabels:
      app: sca-server
  replicas: 1
  template:
    metadata:
      labels:
        app: sca-server
    spec:
      containers:
        - name: sca-server
          image: ghcr.io/fontys-pingmasters/sca-server
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: sca-server-secrets
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: sca-server-secrets
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: sca-server-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sca-server-secrets
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sca-server-secrets
                  key: JWT_SECRET
            - name: JWT_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: sca-server-secrets
                  key: JWT_EXPIRES_IN
            - name: JWT_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: sca-server-secrets
                  key: JWT_AUDIENCE
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: sca-server-secrets
                  key: JWT_ISSUER
            - name: FRONT_END_URL
              valueFrom:
                secretKeyRef:
                  name: sca-server-secrets
                  key: FRONT_END_URL
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "250m"